name: ddf-sdr-dev

services:
  api:
    depends_on:
      - mongodb
    build:
      context: ../ddf-sdr-api
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__ServerName=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongodb:27018/${MONGO_DATABASE}?authSource=admin
      - ConnectionStrings__DatabaseName=${MONGO_DATABASE}
      - StudyHistory__DateRange=30
      - ApiVersionUsdmVersionMapping=${API_VERSION_USDM_VERSION_MAPPING}
      - ASPNETCORE_ENVIRONMENT=Development
      - isGroupFilterEnabled=false
      - isAuthEnabled=false
      - CdiscRulesEngine=${CDISC_RULES_ENGINE}
      - CdiscRulesEngineRelativeBinary=${CDISC_RULES_ENGINE_RELATIVE_BINARY}
      - CdiscRulesEngineRelativeCache=${CDISC_RULES_ENGINE_RELATIVE_CACHE}
    volumes:
      - cdisc_rules_engine_cache:${CDISC_RULES_ENGINE}/${CDISC_RULES_ENGINE_RELATIVE_CACHE}
    ports:
      - "8080:80"
    networks:
      - backend

volumes:
  cdisc_rules_engine_cache:
