name: ddf-sdr-dev

services:
  api:
    depends_on:
      - mongodb
    build:
      context: ../ddf-sdr-api
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__ServerName=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongodb:27018/${MONGO_DATABASE}?authSource=admin
      - ConnectionStrings__DatabaseName=${MONGO_DATABASE}
      - StudyHistory__DateRange=30
      - ApiVersionUsdmVersionMapping=${API_VERSION_USDM_VERSION_MAPPING}
      - ASPNETCORE_ENVIRONMENT=Development
      - isGroupFilterEnabled=false
      - isAuthEnabled=false
    ports:
      - "8080:80"
    networks:
      - backend
